# Generated by Django 5.2.8 on 2025-11-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_stockpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketevent',
            name='impact_level',
            field=models.CharField(choices=[('minor', 'Slightly'), ('moderate', 'Moderately'), ('major', 'Significantly'), ('severe', 'Severely')], default='minor', max_length=50),
        ),
    ]
