# Generated by Django 5.2.8 on 2025-11-09 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_marketevent_impact_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketevent',
            name='name',
        ),
    ]
