# Generated by Django 5.2.8 on 2025-11-09 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_marketeventapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketevent',
            name='created_at',
        ),
    ]
