# Generated by Django 5.2.8 on 2025-11-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_remove_marketevent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='volatility_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='volatility_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
