# Generated by Django 5.2.8 on 2025-11-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=100.0),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
