# Generated by Django 5.2.8 on 2025-11-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_balance_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_loan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='loan_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
